/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QueryPacs;

import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author cti
 */
public class QueryPanel extends javax.swing.JPanel {

    public javax.swing.JButton getB_query() {
        return b_query;
    }

    public JTextArea gettxtA_searchResult(){
        return txtA_searchResult;
    }
    
    public JTextField gettxt_querySerieUID(){
        return txt_queryInput;
    }
        
    public JTextField gettxt_queryModality(){
        return txt_queryInput1;
    }
    /**
     * Creates new form QueryPanel
     */
    public QueryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_queryInput = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_queryInput1 = new javax.swing.JTextField();
        b_query = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_searchResult = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(600, 200));
        setPreferredSize(new java.awt.Dimension(600, 200));
        setLayout(new java.awt.BorderLayout());

        jPanel9.setMaximumSize(new java.awt.Dimension(193, 33));
        jPanel9.setLayout(new java.awt.GridLayout(2, 0));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("SerieUID : ");
        jPanel1.add(jLabel1);

        txt_queryInput.setMinimumSize(new java.awt.Dimension(250, 20));
        txt_queryInput.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel1.add(txt_queryInput);

        jPanel9.add(jPanel1);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Modality :");
        jPanel3.add(jLabel2);

        txt_queryInput1.setMinimumSize(new java.awt.Dimension(250, 20));
        txt_queryInput1.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel3.add(txt_queryInput1);

        b_query.setText("Search");
        jPanel3.add(b_query);

        jPanel9.add(jPanel3);

        add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Result"));
        jPanel2.setMaximumSize(new java.awt.Dimension(500, 200));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 200));
        jPanel2.setLayout(new java.awt.BorderLayout());

        txtA_searchResult.setColumns(20);
        txtA_searchResult.setRows(5);
        jScrollPane1.setViewportView(txtA_searchResult);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_query;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA_searchResult;
    private javax.swing.JTextField txt_queryInput;
    private javax.swing.JTextField txt_queryInput1;
    // End of variables declaration//GEN-END:variables
}
